"""Load and write lens tier assignments from tiers.toml."""
from __future__ import annotations

from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore[no-redef]

TIERS_PATH = Path(__file__).resolve().parent / "tiers.toml"


def load_tiers(path: Path | None = None) -> dict[str, str]:
    """Load lens tier assignments from tiers.toml. Returns {lens_name: tier}."""
    p = path or TIERS_PATH
    if not p.exists():
        return {}
    with open(p, "rb") as f:
        data = tomllib.load(f)
    return {name: section["tier"] for name, section in data.items() if "tier" in section}


def write_tiers(tiers: dict[str, str], path: Path | None = None) -> None:
    """Write tier assignments back to tiers.toml."""
    p = path or TIERS_PATH
    lines = ["# Lens tier assignments — auto-generated by `prose-doctor validate --promote`\n"]
    for name, tier in sorted(tiers.items()):
        lines.append(f"\n[{name}]")
        lines.append(f'tier = "{tier}"')
    lines.append("")  # trailing newline
    p.write_text("\n".join(lines))
